export const PLAYERS = [
    { id: 1, firstName: 'Jason', lastName: 'Owen', group: '6u', bats: 'right', throws: 'right' },
    { id: 2, firstName: 'Tim', lastName: 'Ledford', group: '6u', bats: 'right', throws: 'right' },
    { id: 3, firstName: 'Mike', lastName: 'Dick', group: '6u', bats: 'right', throws: 'right' },
    { id: 4, firstName: 'Brent', lastName: 'Lyons', group: '6u', bats: 'right', throws: 'right' },
    { id: 5, firstName: 'Jay', lastName: 'Wingo', group: '6u', bats: 'right', throws: 'right' },
    { id: 6, firstName: 'Easton', lastName: 'Morrow', group: '6u', bats: 'right', throws: 'right' },
    { id: 7, firstName: 'Donald', lastName: 'Wilson', group: '6u', bats: 'right', throws: 'right' },
    { id: 8, firstName: 'Brandon', lastName: 'Gibson', group: '6u', bats: 'right', throws: 'right' },
    { id: 9, firstName: 'Nick', lastName: 'Malone', group: '6u', bats: 'right', throws: 'right' },
    { id: 10, firstName: 'Jarred', lastName: 'Hargis', group: '6u', bats: 'right', throws: 'right' },
    { id: 11, firstName: 'Jason', lastName: 'Owen', group: '8u', bats: 'right', throws: 'right' },
    { id: 12, firstName: 'Tim', lastName: 'Ledford', group: '8u', bats: 'right', throws: 'right' },
    { id: 13, firstName: 'Mike', lastName: 'Dick', group: '8u', bats: 'right', throws: 'right' },
    { id: 14, firstName: 'Brent', lastName: 'Lyons', group: '8u', bats: 'right', throws: 'right' },
    { id: 15, firstName: 'Jay', lastName: 'Wingo', group: '8u', bats: 'right', throws: 'right' },
    { id: 16, firstName: 'Easton', lastName: 'Morrow', group: '8u', bats: 'right', throws: 'right' },
    { id: 17, firstName: 'Donald', lastName: 'Wilson', group: '8u', bats: 'right', throws: 'right' },
    { id: 18, firstName: 'Brandon', lastName: 'Gibson', group: '8u', bats: 'right', throws: 'right' },
    { id: 19, firstName: 'Nick', lastName: 'Malone', group: '8u', bats: 'right', throws: 'right' },
    { id: 20, firstName: 'Jarred', lastName: 'Hargis', group: '8u', bats: 'right', throws: 'right' },
]