export const PLAYERS = [
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 1, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 2, firstName: 'David', lastName: 'Ledford', pos: '2nd', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 3, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 4, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 5, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 6, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 7, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 8, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 9, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 10, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 11, firstName: 'Jason', lastName: 'Reed', pos: 'O', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 12, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 13, firstName: 'Michael', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 14, firstName: 'Reed', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 15, firstName: 'Wayne', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 16, firstName: 'Mike', lastName: 'Shultz', pos: '3rd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 17, firstName: 'Brent', lastName: 'Thomas', pos: 'P', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 18, firstName: 'Craig', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 19, firstName: 'Gary', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 20, firstName: 'David', lastName: 'Wilson', pos: 'RF', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 21, firstName: 'Rudy', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 22, firstName: 'Gabe', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 23, firstName: 'Jack', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 24, firstName: 'Jason', lastName: 'Cross', pos: 'O', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 25, firstName: 'Omar', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 26, firstName: 'Edgar', lastName: 'Ruiz', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 27, firstName: 'Jimmey', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 28, firstName: 'Timothy', lastName: 'Shanks', pos: '2nd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 29, firstName: 'Mitchel', lastName: 'Bowman', pos: '3rd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 30, firstName: 'Brendan', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 31, firstName: 'Jonathan', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 32, firstName: 'Swayer', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 33, firstName: 'Darrell', lastName: 'Wilson', pos: 'RF', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 34, firstName: 'Thomas', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 35, firstName: 'Nicholas', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 36, firstName: 'James', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 37, firstName: 'Jacob', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 38, firstName: 'Kaeden', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 39, firstName: 'Russel', lastName: 'Dick', pos: 'O', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 40, firstName: 'Jason', lastName: 'Jackson', pos: '1st', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 41, firstName: 'Tim', lastName: 'Wallen', pos: '2nd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 42, firstName: 'Peter', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 43, firstName: 'Derrik', lastName: 'Smalls', pos: 'P', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 44, firstName: 'Jax', lastName: 'Golliher', pos: 'C', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 45, firstName: 'Asher', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 46, firstName: 'Donny', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 47, firstName: 'Adam', lastName: 'Hudson', pos: 'LF', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 48, firstName: 'Bobby', lastName: 'Shoemaker', pos: 'CF', bats: 'left', throws: 'left' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 49, firstName: 'Samuel', lastName: 'Reed', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 50, firstName: 'Jackson', lastName: 'Owens', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 51, firstName: 'Hank', lastName: 'Geomangie', pos: 'O', bats: 'right', throws: 'right' },
    { drafted: false, evaluations: [], group: "6U", ppi: 0, id: 52, firstName: 'Mark', lastName: 'Shelton', pos: 'O', bats: 'left', throws: 'left' },
    // Evaled 6U below
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.3, id: 1, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.4, id: 2, firstName: 'David', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.8, id: 3, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.8, id: 4, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.2, id: 5, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.7, id: 6, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.1, id: 7, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.7, id: 8, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.3, id: 9, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.5, id: 10, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.9, id: 11, firstName: 'Jason', lastName: 'Reed', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.9, id: 12, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.4, id: 13, firstName: 'Michael', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.3, id: 14, firstName: 'Reed', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.4, id: 15, firstName: 'Wayne', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.8, id: 16, firstName: 'Mike', lastName: 'Shultz', pos: '3rd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.8, id: 17, firstName: 'Brent', lastName: 'Thomas', pos: 'P', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.2, id: 18, firstName: 'Craig', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.7, id: 19, firstName: 'Gary', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.1, id: 20, firstName: 'David', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.7, id: 21, firstName: 'Rudy', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.3, id: 22, firstName: 'Gabe', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.5, id: 23, firstName: 'Jack', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.9, id: 24, firstName: 'Jason', lastName: 'Cross', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.9, id: 25, firstName: 'Omar', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.4, id: 26, firstName: 'Edgar', lastName: 'Ruiz', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.3, id: 27, firstName: 'Jimmey', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.4, id: 28, firstName: 'Timothy', lastName: 'Shanks', pos: '2nd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.8, id: 29, firstName: 'Mitchel', lastName: 'Bowman', pos: '3rd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.8, id: 30, firstName: 'Brendan', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.2, id: 31, firstName: 'Jonathan', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.7, id: 32, firstName: 'Swayer', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.1, id: 33, firstName: 'Darrell', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.7, id: 34, firstName: 'Thomas', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.3, id: 35, firstName: 'Nicholas', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.5, id: 36, firstName: 'James', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.9, id: 37, firstName: 'Jacob', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.9, id: 38, firstName: 'Kaeden', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.4, id: 39, firstName: 'Russel', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.3, id: 40, firstName: 'Jason', lastName: 'Jackson', pos: '1st', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.4, id: 41, firstName: 'Tim', lastName: 'Wallen', pos: '2nd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.8, id: 42, firstName: 'Peter', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.8, id: 43, firstName: 'Derrik', lastName: 'Smalls', pos: 'P', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.2, id: 44, firstName: 'Jax', lastName: 'Golliher', pos: 'C', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 3.7, id: 45, firstName: 'Asher', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.1, id: 46, firstName: 'Donny', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.7, id: 47, firstName: 'Adam', lastName: 'Hudson', pos: 'LF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 0.3, id: 48, firstName: 'Bobby', lastName: 'Shoemaker', pos: 'CF', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 4.5, id: 49, firstName: 'Samuel', lastName: 'Reed', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 2.9, id: 50, firstName: 'Jackson', lastName: 'Owens', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.9, id: 51, firstName: 'Hank', lastName: 'Geomangie', pos: 'O', bats: 'right', throws: 'right' },
    // { drafted: false, evaluations: [], group: "6U", ppi: 1.4, id: 52, firstName: 'Mark', lastName: 'Shelton', pos: 'O', bats: 'right', throws: 'right' },
    // 8U below
    // { group: "8U", ppi: 1.3, id: 1, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.4, id: 2, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.8, id: 3, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.8, id: 4, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.2, id: 5, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.7, id: 6, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.1, id: 7, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.7, id: 8, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.3, id: 9, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.5, id: 10, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.9, id: 11, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.9, id: 12, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.4, id: 13, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.3, id: 14, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.4, id: 15, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.8, id: 16, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.8, id: 17, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.2, id: 18, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.7, id: 19, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.1, id: 20, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.7, id: 21, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.3, id: 22, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.5, id: 23, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.9, id: 24, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.9, id: 25, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.4, id: 26, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.3, id: 27, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.4, id: 28, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.8, id: 29, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.8, id: 30, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.2, id: 31, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.7, id: 32, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.1, id: 33, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.7, id: 34, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.3, id: 35, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.5, id: 36, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.9, id: 37, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.9, id: 38, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.4, id: 39, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.3, id: 40, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.4, id: 41, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.8, id: 42, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.8, id: 43, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.2, id: 44, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 3.7, id: 45, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.1, id: 46, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.7, id: 47, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 0.3, id: 48, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 4.5, id: 49, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 2.9, id: 50, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.9, id: 51, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "8U", ppi: 1.4, id: 52, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // 10U below
    // { group: "10U", ppi: 1.3, id: 1, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.4, id: 2, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.8, id: 3, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.8, id: 4, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.2, id: 5, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.7, id: 6, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.1, id: 7, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.7, id: 8, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.3, id: 9, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.5, id: 10, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.9, id: 11, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.9, id: 12, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.4, id: 13, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.3, id: 14, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.4, id: 15, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.8, id: 16, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.8, id: 17, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.2, id: 18, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.7, id: 19, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.1, id: 20, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.7, id: 21, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.3, id: 22, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.5, id: 23, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.9, id: 24, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.9, id: 25, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.4, id: 26, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.3, id: 27, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.4, id: 28, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.8, id: 29, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.8, id: 30, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.2, id: 31, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.7, id: 32, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.1, id: 33, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.7, id: 34, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.3, id: 35, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.5, id: 36, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.9, id: 37, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.9, id: 38, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.4, id: 39, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.3, id: 40, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.4, id: 41, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.8, id: 42, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.8, id: 43, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.2, id: 44, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 3.7, id: 45, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.1, id: 46, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.7, id: 47, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 0.3, id: 48, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 4.5, id: 49, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 2.9, id: 50, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.9, id: 51, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "10U", ppi: 1.4, id: 52, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // 12U below
    // { group: "12U", ppi: 1.3, id: 1, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.4, id: 2, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.8, id: 3, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.8, id: 4, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.2, id: 5, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.7, id: 6, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.1, id: 7, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.7, id: 8, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.3, id: 9, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.5, id: 10, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.9, id: 11, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.9, id: 12, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.4, id: 13, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.3, id: 14, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.4, id: 15, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.8, id: 16, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.8, id: 17, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.2, id: 18, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.7, id: 19, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.1, id: 20, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.7, id: 21, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.3, id: 22, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.5, id: 23, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.9, id: 24, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.9, id: 25, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.4, id: 26, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.3, id: 27, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.4, id: 28, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.8, id: 29, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.8, id: 30, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.2, id: 31, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.7, id: 32, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.1, id: 33, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.7, id: 34, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.3, id: 35, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.5, id: 36, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.9, id: 37, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.9, id: 38, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.4, id: 39, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.3, id: 40, firstName: 'Jason', lastName: 'Owen', pos: '1st', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.4, id: 41, firstName: 'Tim', lastName: 'Ledford', pos: '2nd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.8, id: 42, firstName: 'Mike', lastName: 'Dick', pos: '3rd', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.8, id: 43, firstName: 'Brent', lastName: 'Lyons', pos: 'P', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.2, id: 44, firstName: 'Jay', lastName: 'Wingo', pos: 'C', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 3.7, id: 45, firstName: 'Easton', lastName: 'Morrow', pos: 'SS', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.1, id: 46, firstName: 'Donald', lastName: 'Wilson', pos: 'RF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.7, id: 47, firstName: 'Brandon', lastName: 'Gibson', pos: 'LF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 0.3, id: 48, firstName: 'Nick', lastName: 'Malone', pos: 'CF', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 4.5, id: 49, firstName: 'Jarred', lastName: 'Hargis', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 2.9, id: 50, firstName: 'Jason', lastName: 'Owen', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.9, id: 51, firstName: 'Tim', lastName: 'Ledford', pos: 'O', bats: 'right', throws: 'right' },
    // { group: "12U", ppi: 1.4, id: 52, firstName: 'Mike', lastName: 'Dick', pos: 'O', bats: 'right', throws: 'right' },
]